carts/urls.py
from django.urls import path
from . import views

urlpatterns=[

    path('',views.cart_detail,name="cart_detail"),
    path('add/<int:product_id>/',views.add_to_cart,name="add_to_cart"),
    path('remove/<int:item_id>/',views.remove_from_cart,name="remove_from_cart"),
    path('update/<int:item_id>/',views.update_cart_quantity,name="update_cart_quantity"),


]

orders/urls.py
from django.urls import path
from . import views
app_name = 'orders'
urlpatterns = [
    path('create/', views.create_order, name='create_order'),
    path('<int:order_id>/', views.order_detail, name='order_detail'),
    path('', views.order_list, name='order_list'),
    path('stripe/checkout/<int:order_id>/', views.stripe_checkout, name='stripe_checkout'),
    path('payment/success/<int:order_id>/', views.payment_success, name='payment_success'),
    path('payment/cancel/<int:order_id>/', views.payment_cancel, name='payment_cancel'),

]

project2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls')),
    path('cart/',include('carts.urls')),
    path('accounts/',include('accounts.urls')),    
    path('orders/',include('orders.urls')),  
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product

class Cart(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Cartitem(models.Model):
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE,related_name='items')
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.PositiveIntegerField(default=1)

    def total_price(self):
        return self.product.price * self.quantity

carts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from products.models import Product
from .models import Cart,Cartitem

def get_cart(user):
    cart,created=Cart.objects.get_or_create(user=user)
    return cart

@login_required
def add_to_cart(request,product_id):
    product=get_object_or_404(Product,id=product_id)
    cart=get_cart(request.user)
    cart_item,created=Cartitem.objects.get_or_create(cart=cart,product=product)
    if not created :
        cart_item.quantity+=1
    cart_item.save()

    return redirect('cart_detail')

@login_required
def cart_detail(request):
    cart=get_cart(request.user)
    items=cart.items.all()

    total=sum(item.total_price() for item in items)

    return render(request,'carts/cart_detail.html',{ 'cart':cart,'items':items,'total':total})

@login_required
def remove_from_cart(request,item_id):
    item=get_object_or_404(Cartitem,id=item_id)
    item.delete()
    return redirect('cart_detail')

@login_required
def update_cart_quantity(request,item_id):
    item=get_object_or_404(Cartitem,id=item_id)
    if request.method=='POST':
        quantity=int(request.POST.get('quantity'))
        if quantity>0:
            item.quantity=quantity
            item.save()
    return redirect('cart_detail')

templates/carts/cart_detail.html
{% extends 'base.html' %}
{% block title %}My Cart{% endblock %}

{% block content %}
<div class="container mt-5">

    <h3 class="mb-4">🛒 Shopping Cart</h3>
    
    <div class="d-grid gap-2 d-md-flex justify-content-md-end"></div>
        <a href="{% url 'home' %}" class="btn btn-primary">
        <i class="bi bi-cart-plus"></i> Add More Products
        </a>
    </div>


    {% if items %}
    <div class="card shadow-sm">
        <div class="card-body">

            <table class="table table-bordered align-middle">
                <thead class="table-dark">
                    <tr>
                        <th>Product</th>
                        <th width="120">Price</th>
                        <th width="150">Quantity</th>
                        <th width="120">Subtotal</th>
                        <th width="100">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in items %}
                    <tr>
                        <td>
                            <div class="d-flex align-items-center">
                                <img src="{{ item.product.image.url }}"
                                     class="rounded border me-2"
                                     width="60" height="60"
                                     style="object-fit: cover;">
                                <strong>{{ item.product.name }}</strong>
                            </div>
                        </td>

                        <td>₹{{ item.product.price }}</td>

                        <td>
                            <form method="POST"
                                  action="{% url 'update_cart_quantity' item.id %}">
                                {% csrf_token %}
                                <input type="number"
                                       name="quantity"
                                       value="{{ item.quantity }}"
                                       min="1"
                                       class="form-control form-control-sm mb-1">
                                <button class="btn btn-sm btn-outline-primary w-100">
                                    Update
                                </button>
                            </form>
                        </td>

                        <td>₹{{ item.total_price }}</td>

                        <td>
                            <a href="{% url 'remove_from_cart' item.id %}"
                               class="btn btn-sm btn-danger w-100">
                                Remove
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <div class="row align-items-center mt-4">

                
                <div class="col-md-6 mb-3 mb-md-0">
                    <a href="{% url 'home' %}" class="btn btn-outline-secondary">
                        ← Back to Products
                    </a>

                    <a href="{% url 'orders:order_list' %}"
                       class="btn btn-outline-dark ms-2">
                        📦 My Orders
                    </a>
                </div>

                <div class="col-md-6 text-end">
                    <h5 class="mb-3">
                        Total Amount:
                        <span class="text-success fw-bold">
                            ₹{{ total }}
                        </span>
                    </h5>

                    <form method="POST"
                          action="{% url 'orders:create_order' %}"
                          class="d-inline">
                        {% csrf_token %}
                        <input type="hidden" name="payment_method" value="cod">
                        <button type="submit"
                                class="btn btn-outline-dark me-2 px-4">
                            Cash on Delivery
                        </button>
                    </form>

                  
                    <form method="POST"
                          action="{% url 'orders:create_order' %}"
                          class="d-inline">
                        {% csrf_token %}
                        <input type="hidden" name="payment_method" value="stripe">
                        <button type="submit"
                                class="btn btn-success px-4">
                            Pay with Stripe 💳
                        </button>
                    </form>

                </div>
            </div>

        </div>
    </div>

    {% else %}
   
    <div class="alert alert-info text-center">
        <h5>Your cart is empty 🛍️</h5>
        <a href="{% url 'home' %}" class="btn btn-primary mt-2">
            Continue Shopping
        </a>
    </div>
    {% endif %}

</div>
{% endblock %}